# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="custom_theme"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(compleat debian dircycle extract)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games
export EDITOR="vim"

alias ls="ls -la --color=always"
alias s="tmux attach || tmux new-session"
alias t="tmux attach || tmux new-session"
alias su="sudo -s"
alias vi="vim -p"
alias mkdir="mkdir -p"
alias free="free -m"
alias du="du -h"
alias df="df -h"
alias pgrep="pgrep -l"
alias grep="egrep"

alias -g G='|egrep -i'

# Keep 100000 lines of history within the shell and save it to ~/.zsh_history:
setopt histignorealldups histreduceblanks histverify sharehistory
HISTSIZE=100000
SAVEHIST=100000

